import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="bg-black fixed bottom-0 text-white w-full p-4 text-center">
          <h2 className="text-lg font-semibold">Features Coming Soon</h2>
          <ul className="mt-2 space-y-1">
            <li>- Right/long click to add the isle</li>
            <li>Option to change the isle</li>
            <li>- Pick your favorite supermarket</li>
            <li>- Mobile native version. </li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
